# Generated by Django 3.2.9 on 2022-02-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airquality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.CharField(max_length=25)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
            ],
        ),
    ]
